[keyboard]
name = "rmk-keyboard"
product_name = "rmk-keyboard"
vendor_id = 0x4743
product_id = 0x5942
manufacturer = "RMK"
chip = "nrf52840"

[matrix]
row_pins = ["P0_06", "P0_08", "P1_01", "P1_02", "P1_07"]
col_pins = ["P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_11", "P1_04","P1_06", "P0_31", "P0_29", "P0_02", "P1_15", "P1_13"]

[layout]
rows = 5
cols = 13
layers = 4  # 改成4层（0,1,2,3）
keymap = [
    # 第0层：基础层
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backslash", "Backspace"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LeftBracket", "RightBracket"],
        ["LayerTap(2, CapsLock)", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "LayerTap(2, Enter)"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Up", "Slash", "RShift"],
        ["LCtrl", "LGui", "LAlt", "Space", "Space", "Mo(1)", "No", "Mo(3)", "Space", "Left", "Down", "Right", "RCtrl"]
    ],
    # 第1层：Fn层
    [
        ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["To(3)", "No", "No", "To(0)", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"]
    ],
    # 第2层：Sleep/PrtSc层
    [
        ["Sleep", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "PrintScreen"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "RmToggle"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["Home", "End", "PageUp", "PageDown", "No", "No", "No", "No", "No", "RmPrev", "RmVald", "RmValu", "RmNext"]
    ],
    # 第3层：数字小键盘层
    [
        ["Escape", "KpMinus", "KpPlus", "KpSlash", "Kp1", "Kp2", "Kp3", "Kp4", "Kp5", "Kp6", "Kp7", "Kp8", "Backspace"],
        ["Kp7", "Kp8", "Kp9", "Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O"],
        ["Kp4", "Kp5", "Kp6", "KpAsterisk", "A", "S", "D", "F", "G", "H", "J", "K", "L"],
        ["Kp1", "Kp2", "Kp3", "LShift", "Z", "X", "C", "V", "B", "N", "M", "P", "Backslash"],
        ["Backspace", "KpDot", "Kp0", "LCtrl", "LGui", "Mo(1)", "No", "LAlt", "Space", "Left", "Down", "Up", "Right"]
    ]
]

[ble]
enabled = true
# vddh has an internal voltage divider
# battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false
