[keyboard]
name = "rmk-planck59"
product_name = "rmk-planck59"
vendor_id = 0x4743
product_id = 0x5942
manufacturer = "RMK"
chip = "esp32s3"
usb_enable = true

[matrix]
# Row and col pins are mandatory
row_pins = ["GPIO6", "GPIO7", "GPIO18", "GPIO21"]
col_pins = ["GPIO3", "GPIO4", "GPIO5"]

# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 5
cols = 13
layers = 4  # 改成4层（0,1,2,3）
keymap = [
    # 第0层：基础层
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backslash", "Backspace"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LeftBracket", "RightBracket"],
        ["TD(0)", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "TD(1)"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Up", "Slash", "TD(2)"],
        ["LCtrl", "LGui", "LAlt", "Space", "Space", "Mo(1)", "No", "Mo(3)", "Space", "Left", "Down", "Right", "RCtrl"]
    ],
    # 第1层：Fn层
    [
        ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["To(3)", "No", "No", "To(0)", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"]
    ],
    # 第2层：Sleep/PrtSc层
    [
        ["Stop", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "PrintScreen"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
        ["Home", "End", "PageUp", "PageDown", "No", "No", "No", "No", "No", "No", "No", "No", "No"]
    ],
    # 第3层：数字小键盘层
    [
        ["Escape", "KpMinus", "KpPlus", "KpSlash", "Kp1", "Kp2", "Kp3", "Kp4", "Kp5", "Kp6", "Kp7", "Kp8", "Backspace"],
        ["Kp7", "Kp8", "Kp9", "Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O"],
        ["Kp4", "Kp5", "Kp6", "KpAsterisk", "A", "S", "D", "F", "G", "H", "J", "K", "L"],
        ["Kp1", "Kp2", "Kp3", "LShift", "Z", "X", "C", "V", "B", "N", "M", "P", "Backslash"],
        ["Backspace", "KpDot", "Kp0", "LCtrl", "LGui", "Mo(1)", "No", "LAlt", "Space", "Left", "Down", "Up", "Right"]
    ]
]

[ble]
enabled = true